language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
deploy:
- provider: script
  script: python tools/map_coloring.py
  on:
    branch: master
env:
  global:
  - secure: Wh8TgsW6VnS84IHL5jP0eQ40twCM+MTcv3zXu7Q1+GBC6PnN+hfbHs+vT4JzymVQsUn9yEPBJNn9wberaRwV+j3Lk9Vov+6YOdFe0oaS6W7A4x5tDdpMOJqWXtux4gfxI5500KepevSBhu6qscedHiIrEBV1L/bZdjzF/K24nf7/R6ZU5uV/iMIV6rJwovkKtIyI+u4do1G1iQNht5yMZPRLIj8Tg4Pl8mKmXYtQJonbd05LRYp3wfNBTc500S4DG8Q0Q4dYT1E4H+GISW8x1kk9/1drbqz9yJ9JZwEpHrBYLlPU4S9lNHxGSwBl0voISKVjaWGL7ag1elVlbzwO57yJqSsksJpsBDb7hGq/SbtnbYWQjuTUvSVL2PG8otYRMKy/qXvgopa2Pz5Yg71tOsKgcSn9aX9hKzyRVn8pFylKWZSL4vhKifexpWSZ/CxSr2Gvg5B3MVwnMCWa2R4vt7QPZZkFy19CwTqDARq2gNKPjDpuXpZIPsLODePnv8VrJbyaHYq8iV5dgafJ1R0ANCnxrzofvgyJqWy1ULTnt8+gYGc/34vjLmgrSL76RXZmrkflRLm5IfJ/o0xZhcaYthmfUodAzcylHUD3nsvh0fg1cMoK30uZPy+a/CZ5nfZ1b0UKvyYBcwy6R0nY+51Ctv1mrtbYk6P/b3H4l6xW0sk=
  - secure: hAMbiv5D7HjPtrH6wWWoy2YplYV1qqoNWtDRYlz6Zh59Mpj+s5RuG44YYKM6CJYXrFhdqPk5gq3P1xA9cKV6ZI3Bu3M9mAiGbHwEthF0QOA05IQfBhYEpZm5auIMc0bjVjp4JGPt/lC1+x/rfS42brwXjgSS7wHNnlRVhxdfztQ4dvWKzEMieNzIvNXqrD02eLWnbR3ykopyq6iFWKRlGqxN4kP/1oteQjPHoMvzSM2R4xRhTX+HvW1hlPfcEsbURmVZsXOrXQB39ObwsPTD9XSFqtcXiJxFhItm0BcwAF1EZc31RvXnZZDv0cR/8tkXVTKbMiNNv+XqlJZkALaE8s86YoPogxw/S2RDzTBmPPldgunXDduLZ1EYW2/Lji4fANjEbvqvSa1ZL7yfbPGOT7xvx4Q5eeXDrBjx+o0wKfgrdRgqYULXWmcM850d6oDUE02MceIhQoV+9YoCupc51NEw48rWV0fY79q1CD+iRPdYgi0BTO0CCC5UrUykTI078DhfA5L9SQrZP3pNNUmnwh79nlW7GdBJm9XegkPY5VhMBPDGB5e1OXjyJePNv5WS0nbN5yegPM2tnqwZzWpPzvj7WiQKeXZIRn29k3ZPzzm/MUjQx8WoAXJsAyt9Xcm335jtk3/S0Uyuv/I/MtiTAeZEZsqyhWpGn1rA2A8SLYA=
